[package]
name = "client"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
futures-channel = "0.3.28"
tokio-tungstenite = "0.29.0"
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["full"] }
color-eyre = "0.6.3"
tungstenite = "0.29.0"
log = "0.4.32"
env_logger = "0.11"
chatter_protocol = { path = "../protocol", version = "0.2.0" }
serde_json = "1.0.150"
clap = { version = "4", features = ["derive"] }
bytes = "1"
chrono = "0.4"
egui = "0.35"
eframe = { version = "0.35", default-features = false, features = ["default_fonts", "glow"] }
egui_extras = "0.35"
